name = "random_name_5678"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "random_name_5678_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "random_name_5678.wasm"
command = "npm run build:release"
